server:
  port: 8771
spring:
  application:
    name: oauth2-service
  security:
    user:
      name: admin
      password: 1234554321
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://47.94.144.123:3306/react_article?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: HdY_1927*
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    hostname: localhost:8761
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/