server:
  port: 8771
spring:
  application:
    name: oauth2-service
  security:
    user:
      name: admin
      password: admin2018*
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://118.24.147.11:3306/article?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: huangdeyao
    password: HdY_1927*
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    hostname: 47.94.144.123:8761
    instance-id: 47.94.144.123:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
        defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/

