server:
  port: 8771
spring:
  application:
    name: feign-service
  security:
    user:
      name: admin
      password: admin2018*
eureka:
  instance:
    hostname: eureka.yrclubs.com
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/