server:
  port: 8765
spring:
  application:
    name: feign-service
  security:
    user:
      name: admin
      password: 1234554321
eureka:
  instance:
    hostname: eureka.yrclubs.com
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8766/sso/user
      prefer-token-info: false