server:
  port: 8765
spring:
  application:
    name: feign-service
  security:
    user:
      name: admin
      password: admin2018*
eureka:
  instance:
     hostname: 47.94.144.123:8761
     instance-id: 47.94.144.123:${server.port}
     prefer-ip-address: true
  client:
    serviceUrl:
        defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/

