server:
  port: 8766
spring:
  application:
    name: zuul-service
  security:
    user:
      name: admin
      password: 1234554321
eureka:
  instance:
    hostname: eureka.yrclubs.com
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/
zuul:
  routes:
    storage:
      path: /storage/**
      serviceId: storage-service
      sensitiveHeaders:
    oauth:
      path: /sso/**
      serviceId: oauth2-service
      sensitiveHeaders:
    feign:
      path: /feign/**
      serviceId: feign-service
  add-proxy-headers: true
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
security:
  oauth2:
    client:
      access-token-uri: http://article.yrclubs.com/sso/oauth/token
      user-authorization-uri: http://article.yrclubs.com/sso/oauth/authorize
      grant-type: article-client
      client-secret: article-secret
      client-id: article-client
    resource:
      user-info-uri: http://article.yrclubs.com/sso/user
      prefer-token-info: false
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

