server:
  port: 8766
spring:
  application:
    name: zuul-service
  security:
    user:
      name: admin
      password: admin2018*
eureka:
  instance:
    hostname: 10.1.9.37:8761
    instance-id: 10.1.9.37:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/
zuul:
  routes:
    storage:
      path: /storage/**
      serviceId: storage-service