server:
  port: 8766
spring:
  application:
    name: zuul-service
  security:
    user:
      name: admin
      password: admin2018*
eureka:
  instance:
    hostname: eureka.yrclubs.com
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/
zuul:
  routes:
    storage:
      path: /storage/**
      serviceId: storage-service
    oauth2:
       path: /oauth2/**
       sensitiveHeaders:
       strip-prefix: true
       serviceId: oauth2-service
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8766/oauth2/oauth/token
      user-authorization-uri: http://localhost:8766/oauth2/oauth/authorize
    resource:
      user-info-uri: http://localhost:8766/oauth2/user
      prefer-token-info: false


