server:
  port: 8770
spring:
  application:
    name: storage-service
  security:
    user:
      name: admin
      password: admin2018*
  servlet:
    multipart:
      max-file-size: 10mb
      max-request-size: 20mb
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://118.24.147.11:3306/article?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: huangdeyao
    password: HdY_1927*
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
        defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/

