server:
  port: 8081
spring:
  application:
    name: storage-service
  security:
    user:
      name: admin
      password: admin2018*
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/article?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hybris
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/

