server:
  port: 9500

spring:
  security:
    user:
      name: admin
      password: admin2018*
  application:
    name: elasticsearch-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/
